const countries: countryData = {
   AD: ['Andorra', 'Andorra la Vella', 'ca'],
   AE: ['United Arab Emirates', 'Abu Dhabi', 'ar'],
   AF: ['Afghanistan', 'Kabul', 'ps'],
   AG: ['Antigua and Barbuda', "Saint John's", 'en'],
   AI: ['Anguilla', 'The Valley', 'en'],
   AL: ['Albania', 'Tirana', 'sq'],
   AM: ['Armenia', 'Yerevan', 'hy'],
   AO: ['Angola', 'Luanda', 'pt'],
   AQ: ['Antarctica', '', ''],
   AR: ['Argentina', 'Buenos Aires', 'es'],
   AS: ['American Samoa', 'Pago Pago', 'en'],
   AT: ['Austria', 'Vienna', 'de'],
   AU: ['Australia', 'Canberra', 'en'],
   AW: ['Aruba', 'Oranjestad', 'nl'],
   AX: ['Åland', 'Mariehamn', 'sv'],
   AZ: ['Azerbaijan', 'Baku', 'az'],
   BA: ['Bosnia and Herzegovina', 'Sarajevo', 'bs'],
   BB: ['Barbados', 'Bridgetown', 'en'],
   BD: ['Bangladesh', 'Dhaka', 'bn'],
   BE: ['Belgium', 'Brussels', 'nl'],
   BF: ['Burkina Faso', 'Ouagadougou', 'fr'],
   BG: ['Bulgaria', 'Sofia', 'bg'],
   BH: ['Bahrain', 'Manama', 'ar'],
   BI: ['Burundi', 'Bujumbura', 'fr'],
   BJ: ['Benin', 'Porto-Novo', 'fr'],
   BL: ['Saint Barthélemy', 'Gustavia', 'fr'],
   BM: ['Bermuda', 'Hamilton', 'en'],
   BN: ['Brunei', 'Bandar Seri Begawan', 'ms'],
   BO: ['Bolivia', 'Sucre', 'es'],
   BQ: ['Bonaire', 'Kralendijk', 'nl'],
   BR: ['Brazil', 'Brasília', 'pt'],
   BS: ['Bahamas', 'Nassau', 'en'],
   BT: ['Bhutan', 'Thimphu', 'dz'],
   BV: ['Bouvet Island', '', 'no'],
   BW: ['Botswana', 'Gaborone', 'en'],
   BY: ['Belarus', 'Minsk', 'be'],
   BZ: ['Belize', 'Belmopan', 'en'],
   CA: ['Canada', 'Ottawa', 'en'],
   CC: ['Cocos [Keeling] Islands', 'West Island', 'en'],
   CD: ['Democratic Republic of the Congo', 'Kinshasa', 'fr'],
   CF: ['Central African Republic', 'Bangui', 'fr'],
   CG: ['Republic of the Congo', 'Brazzaville', 'fr'],
   CH: ['Switzerland', 'Bern', 'de'],
   CI: ['Ivory Coast', 'Yamoussoukro', 'fr'],
   CK: ['Cook Islands', 'Avarua', 'en'],
   CL: ['Chile', 'Santiago', 'es'],
   CM: ['Cameroon', 'Yaoundé', 'en'],
   CN: ['China', 'Beijing', 'zh'],
   CO: ['Colombia', 'Bogotá', 'es'],
   CR: ['Costa Rica', 'San José', 'es'],
   CU: ['Cuba', 'Havana', 'es'],
   CV: ['Cape Verde', 'Praia', 'pt'],
   CW: ['Curacao', 'Willemstad', 'nl'],
   CX: ['Christmas Island', 'Flying Fish Cove', 'en'],
   CY: ['Cyprus', 'Nicosia', 'el'],
   CZ: ['Czech Republic', 'Prague', 'cs'],
   DE: ['Germany', 'Berlin', 'de'],
   DJ: ['Djibouti', 'Djibouti', 'fr'],
   DK: ['Denmark', 'Copenhagen', 'da'],
   DM: ['Dominica', 'Roseau', 'en'],
   DO: ['Dominican Republic', 'Santo Domingo', 'es'],
   DZ: ['Algeria', 'Algiers', 'ar'],
   EC: ['Ecuador', 'Quito', 'es'],
   EE: ['Estonia', 'Tallinn', 'et'],
   EG: ['Egypt', 'Cairo', 'ar'],
   EH: ['Western Sahara', 'El Aaiún', 'es'],
   ER: ['Eritrea', 'Asmara', 'ti'],
   ES: ['Spain', 'Madrid', 'es'],
   ET: ['Ethiopia', 'Addis Ababa', 'am'],
   FI: ['Finland', 'Helsinki', 'fi'],
   FJ: ['Fiji', 'Suva', 'en'],
   FK: ['Falkland Islands', 'Stanley', 'en'],
   FM: ['Micronesia', 'Palikir', 'en'],
   FO: ['Faroe Islands', 'Tórshavn', 'fo'],
   FR: ['France', 'Paris', 'fr'],
   GA: ['Gabon', 'Libreville', 'fr'],
   GB: ['United Kingdom', 'London', 'en'],
   GD: ['Grenada', "St. George's", 'en'],
   GE: ['Georgia', 'Tbilisi', 'ka'],
   GF: ['French Guiana', 'Cayenne', 'fr'],
   GG: ['Guernsey', 'St. Peter Port', 'en'],
   GH: ['Ghana', 'Accra', 'en'],
   GI: ['Gibraltar', 'Gibraltar', 'en'],
   GL: ['Greenland', 'Nuuk', 'kl'],
   GM: ['Gambia', 'Banjul', 'en'],
   GN: ['Guinea', 'Conakry', 'fr'],
   GP: ['Guadeloupe', 'Basse-Terre', 'fr'],
   GQ: ['Equatorial Guinea', 'Malabo', 'es'],
   GR: ['Greece', 'Athens', 'el'],
   GS: [
     'South Georgia and the South Sandwich Islands',
     'King Edward Point',
     'en',
   ],
   GT: ['Guatemala', 'Guatemala City', 'es'],
   GU: ['Guam', 'Hagåtña', 'en'],
   GW: ['Guinea-Bissau', 'Bissau', 'pt'],
   GY: ['Guyana', 'Georgetown', 'en'],
   HK: ['Hong Kong', 'City of Victoria', 'zh'],
   HM: ['Heard Island and McDonald Islands', '', 'en'],
   HN: ['Honduras', 'Tegucigalpa', 'es'],
   HR: ['Croatia', 'Zagreb', 'hr'],
   HT: ['Haiti', 'Port-au-Prince', 'fr'],
   HU: ['Hungary', 'Budapest', 'hu'],
   ID: ['Indonesia', 'Jakarta', 'id'],
   IE: ['Ireland', 'Dublin', 'ga'],
   IL: ['Israel', 'Jerusalem', 'he'],
   IM: ['Isle of Man', 'Douglas', 'en'],
   IN: ['India', 'New Delhi', 'hi'],
   IO: ['British Indian Ocean Territory', 'Diego Garcia', 'en'],
   IQ: ['Iraq', 'Baghdad', 'ar'],
   IR: ['Iran', 'Tehran', 'fa'],
   IS: ['Iceland', 'Reykjavik', 'is'],
   IT: ['Italy', 'Rome', 'it'],
   JE: ['Jersey', 'Saint Helier', 'en'],
   JM: ['Jamaica', 'Kingston', 'en'],
   JO: ['Jordan', 'Amman', 'ar'],
   JP: ['Japan', 'Tokyo', 'ja'],
   KE: ['Kenya', 'Nairobi', 'en'],
   KG: ['Kyrgyzstan', 'Bishkek', 'ky'],
   KH: ['Cambodia', 'Phnom Penh', 'km'],
   KI: ['Kiribati', 'South Tarawa', 'en'],
   KM: ['Comoros', 'Moroni', 'ar'],
   KN: ['Saint Kitts and Nevis', 'Basseterre', 'en'],
   KP: ['North Korea', 'Pyongyang', 'ko'],
   KR: ['South Korea', 'Seoul', 'ko'],
   KW: ['Kuwait', 'Kuwait City', 'ar'],
   KY: ['Cayman Islands', 'George Town', 'en'],
   KZ: ['Kazakhstan', 'Astana', 'kk'],
   LA: ['Laos', 'Vientiane', 'lo'],
   LB: ['Lebanon', 'Beirut', 'ar'],
   LC: ['Saint Lucia', 'Castries', 'en'],
   LI: ['Liechtenstein', 'Vaduz', 'de'],
   LK: ['Sri Lanka', 'Colombo', 'si'],
   LR: ['Liberia', 'Monrovia', 'en'],
   LS: ['Lesotho', 'Maseru', 'en'],
   LT: ['Lithuania', 'Vilnius', 'lt'],
   LU: ['Luxembourg', 'Luxembourg', 'fr'],
   LV: ['Latvia', 'Riga', 'lv'],
   LY: ['Libya', 'Tripoli', 'ar'],
   MA: ['Morocco', 'Rabat', 'ar'],
   MC: ['Monaco', 'Monaco', 'fr'],
   MD: ['Moldova', 'Chișinău', 'ro'],
   ME: ['Montenegro', 'Podgorica', 'sr'],
   MF: ['Saint Martin', 'Marigot', 'en'],
   MG: ['Madagascar', 'Antananarivo', 'fr'],
   MH: ['Marshall Islands', 'Majuro', 'en'],
   MK: ['North Macedonia', 'Skopje', 'mk'],
   ML: ['Mali', 'Bamako', 'fr'],
   MM: ['Myanmar [Burma]', 'Naypyidaw', 'my'],
   MN: ['Mongolia', 'Ulan Bator', 'mn'],
   MO: ['Macao', 'Macao', 'zh'],
   MP: ['Northern Mariana Islands', 'Saipan', 'en'],
   MQ: ['Martinique', 'Fort-de-France', 'fr'],
   MR: ['Mauritania', 'Nouakchott', 'ar'],
   MS: ['Montserrat', 'Plymouth', 'en'],
   MT: ['Malta', 'Valletta', 'mt'],
   MU: ['Mauritius', 'Port Louis', 'en'],
   MV: ['Maldives', 'Malé', 'dv'],
   MW: ['Malawi', 'Lilongwe', 'en'],
   MX: ['Mexico', 'Mexico City', 'es'],
   MY: ['Malaysia', 'Kuala Lumpur', 'ms'],
   MZ: ['Mozambique', 'Maputo', 'pt'],
   NA: ['Namibia', 'Windhoek', 'en'],
   NC: ['New Caledonia', 'Nouméa', 'fr'],
   NE: ['Niger', 'Niamey', 'fr'],
   NF: ['Norfolk Island', 'Kingston', 'en'],
   NG: ['Nigeria', 'Abuja', 'en'],
   NI: ['Nicaragua', 'Managua', 'es'],
   NL: ['Netherlands', 'Amsterdam', 'nl'],
   NO: ['Norway', 'Oslo', 'no'],
   NP: ['Nepal', 'Kathmandu', 'ne'],
   NR: ['Nauru', 'Yaren', 'en'],
   NU: ['Niue', 'Alofi', 'en'],
   NZ: ['New Zealand', 'Wellington', 'en'],
   OM: ['Oman', 'Muscat', 'ar'],
   PA: ['Panama', 'Panama City', 'es'],
   PE: ['Peru', 'Lima', 'es'],
   PF: ['French Polynesia', 'Papeetē', 'fr'],
   PG: ['Papua New Guinea', 'Port Moresby', 'en'],
   PH: ['Philippines', 'Manila', 'en'],
   PK: ['Pakistan', 'Islamabad', 'en'],
   PL: ['Poland', 'Warsaw', 'pl'],
   PM: ['Saint Pierre and Miquelon', 'Saint-Pierre', 'fr'],
   PN: ['Pitcairn Islands', 'Adamstown', 'en'],
   PR: ['Puerto Rico', 'San Juan', 'es'],
   PS: ['Palestine', 'Ramallah', 'ar'],
   PT: ['Portugal', 'Lisbon', 'pt'],
   PW: ['Palau', 'Ngerulmud', 'en'],
   PY: ['Paraguay', 'Asunción', 'es'],
   QA: ['Qatar', 'Doha', 'ar'],
   RE: ['Réunion', 'Saint-Denis', 'fr'],
   RO: ['Romania', 'Bucharest', 'ro'],
   RS: ['Serbia', 'Belgrade', 'sr'],
   RU: ['Russia', 'Moscow', 'ru'],
   RW: ['Rwanda', 'Kigali', 'rw'],
   SA: ['Saudi Arabia', 'Riyadh', 'ar'],
   SB: ['Solomon Islands', 'Honiara', 'en'],
   SC: ['Seychelles', 'Victoria', 'fr'],
   SD: ['Sudan', 'Khartoum', 'ar'],
   SE: ['Sweden', 'Stockholm', 'sv'],
   SG: ['Singapore', 'Singapore', 'en'],
   SH: ['Saint Helena', 'Jamestown', 'en'],
   SI: ['Slovenia', 'Ljubljana', 'sl'],
   SJ: ['Svalbard and Jan Mayen', 'Longyearbyen', 'no'],
   SK: ['Slovakia', 'Bratislava', 'sk'],
   SL: ['Sierra Leone', 'Freetown', 'en'],
   SM: ['San Marino', 'City of San Marino', 'it'],
   SN: ['Senegal', 'Dakar', 'fr'],
   SO: ['Somalia', 'Mogadishu', 'so'],
   SR: ['Suriname', 'Paramaribo', 'nl'],
   SS: ['South Sudan', 'Juba', 'en'],
   ST: ['São Tomé and Príncipe', 'São Tomé', 'pt'],
   SV: ['El Salvador', 'San Salvador', 'es'],
   SX: ['Sint Maarten', 'Philipsburg', 'nl'],
   SY: ['Syria', 'Damascus', 'ar'],
   SZ: ['Swaziland', 'Lobamba', 'en'],
   TC: ['Turks and Caicos Islands', 'Cockburn Town', 'en'],
   TD: ['Chad', "N'Djamena", 'fr'],
   TF: ['French Southern Territories', 'Port-aux-Français', 'fr'],
   TG: ['Togo', 'Lomé', 'fr'],
   TH: ['Thailand', 'Bangkok', 'th'],
   TJ: ['Tajikistan', 'Dushanbe', 'tg'],
   TK: ['Tokelau', 'Fakaofo', 'en'],
   TL: ['East Timor', 'Dili', 'pt'],
   TM: ['Turkmenistan', 'Ashgabat', 'tk'],
   TN: ['Tunisia', 'Tunis', 'ar'],
   TO: ['Tonga', "Nuku'alofa", 'en'],
   TR: ['Turkey', 'Ankara', 'tr'],
   TT: ['Trinidad and Tobago', 'Port of Spain', 'en'],
   TV: ['Tuvalu', 'Funafuti', 'en'],
   TW: ['Taiwan', 'Taipei', 'zh'],
   TZ: ['Tanzania', 'Dodoma', 'sw'],
   UA: ['Ukraine', 'Kyiv', 'uk'],
   UG: ['Uganda', 'Kampala', 'en'],
   UM: ['U.S. Minor Outlying Islands', '', 'en'],
   US: ['United States', 'New York', 'en'],
   UY: ['Uruguay', 'Montevideo', 'es'],
   UZ: ['Uzbekistan', 'Tashkent', 'uz'],
   VA: ['Vatican City', 'Vatican City', 'it'],
   VC: ['Saint Vincent and the Grenadines', 'Kingstown', 'en'],
   VE: ['Venezuela', 'Caracas', 'es'],
   VG: ['British Virgin Islands', 'Road Town', 'en'],
   VI: ['U.S. Virgin Islands', 'Charlotte Amalie', 'en'],
   VN: ['Vietnam', 'Hanoi', 'vi'],
   VU: ['Vanuatu', 'Port Vila', 'bi'],
   WF: ['Wallis and Futuna', 'Mata-Utu', 'fr'],
   WS: ['Samoa', 'Apia', 'sm'],
   XK: ['Kosovo', 'Pristina', 'sq'],
   YE: ['Yemen', "Sana'a", 'ar'],
   YT: ['Mayotte', 'Mamoudzou', 'fr'],
   ZA: ['South Africa', 'Pretoria', 'af'],
   ZM: ['Zambia', 'Lusaka', 'en'],
   ZW: ['Zimbabwe', 'Harare', 'en'],
   ZZ: ['Unknown', 'Unknown', 'en'],
};

export const countryAlphaTwoCodes: countryCodeData = {
   AFG: 'AF',
   ALA: 'AX',
   ALB: 'AL',
   DZA: 'DZ',
   ASM: 'AS',
   AND: 'AD',
   AGO: 'AO',
   AIA: 'AI',
   ATA: 'AQ',
   ATG: 'AG',
   ARG: 'AR',
   ARM: 'AM',
   ABW: 'AW',
   AUS: 'AU',
   AUT: 'AT',
   AZE: 'AZ',
   BHS: 'BS',
   BHR: 'BH',
   BGD: 'BD',
   BRB: 'BB',
   BLR: 'BY',
   BEL: 'BE',
   BLZ: 'BZ',
   BEN: 'BJ',
   BMU: 'BM',
   BTN: 'BT',
   BOL: 'BO',
   BES: 'BQ',
   BIH: 'BA',
   BWA: 'BW',
   BVT: 'BV',
   BRA: 'BR',
   IOT: 'IO',
   BRN: 'BN',
   BGR: 'BG',
   BFA: 'BF',
   BDI: 'BI',
   CPV: 'CV',
   KHM: 'KH',
   CMR: 'CM',
   CAN: 'CA',
   CYM: 'KY',
   CAF: 'CF',
   TCD: 'TD',
   CHL: 'CL',
   CHN: 'CN',
   CXR: 'CX',
   CCK: 'CC',
   COL: 'CO',
   COM: 'KM',
   COG: 'CG',
   COD: 'CD',
   COK: 'CK',
   CRI: 'CR',
   CIV: 'CI',
   HRV: 'HR',
   CUB: 'CU',
   CUW: 'CW',
   CYP: 'CY',
   CZE: 'CZ',
   DNK: 'DK',
   DJI: 'DJ',
   DMA: 'DM',
   DOM: 'DO',
   ECU: 'EC',
   EGY: 'EG',
   SLV: 'SV',
   GNQ: 'GQ',
   ERI: 'ER',
   EST: 'EE',
   SWZ: 'SZ',
   ETH: 'ET',
   FLK: 'FK',
   FRO: 'FO',
   FJI: 'FJ',
   FIN: 'FI',
   FRA: 'FR',
   GUF: 'GF',
   PYF: 'PF',
   ATF: 'TF',
   GAB: 'GA',
   GMB: 'GM',
   GEO: 'GE',
   DEU: 'DE',
   GHA: 'GH',
   GIB: 'GI',
   GRC: 'GR',
   GRL: 'GL',
   GRD: 'GD',
   GLP: 'GP',
   GUM: 'GU',
   GTM: 'GT',
   GGY: 'GG',
   GIN: 'GN',
   GNB: 'GW',
   GUY: 'GY',
   HTI: 'HT',
   HMD: 'HM',
   VAT: 'VA',
   HND: 'HN',
   HKG: 'HK',
   HUN: 'HU',
   ISL: 'IS',
   IND: 'IN',
   IDN: 'ID',
   IRN: 'IR',
   IRQ: 'IQ',
   IRL: 'IE',
   IMN: 'IM',
   ISR: 'IL',
   ITA: 'IT',
   JAM: 'JM',
   JPN: 'JP',
   JEY: 'JE',
   JOR: 'JO',
   KAZ: 'KZ',
   KEN: 'KE',
   KIR: 'KI',
   PRK: 'KP',
   KOR: 'KR',
   KWT: 'KW',
   KGZ: 'KG',
   LAO: 'LA',
   LVA: 'LV',
   LBN: 'LB',
   LSO: 'LS',
   LBR: 'LR',
   LBY: 'LY',
   LIE: 'LI',
   LTU: 'LT',
   LUX: 'LU',
   MAC: 'MO',
   MDG: 'MG',
   MWI: 'MW',
   MYS: 'MY',
   MDV: 'MV',
   MLI: 'ML',
   MLT: 'MT',
   MHL: 'MH',
   MTQ: 'MQ',
   MRT: 'MR',
   MUS: 'MU',
   MYT: 'YT',
   MEX: 'MX',
   FSM: 'FM',
   MDA: 'MD',
   MCO: 'MC',
   MNG: 'MN',
   MNE: 'ME',
   MSR: 'MS',
   MAR: 'MA',
   MOZ: 'MZ',
   MMR: 'MM',
   NAM: 'NA',
   NRU: 'NR',
   NPL: 'NP',
   NLD: 'NL',
   NCL: 'NC',
   NZL: 'NZ',
   NIC: 'NI',
   NER: 'NE',
   NGA: 'NG',
   NIU: 'NU',
   NFK: 'NF',
   MKD: 'MK',
   MNP: 'MP',
   NOR: 'NO',
   OMN: 'OM',
   PAK: 'PK',
   PLW: 'PW',
   PSE: 'PS',
   PAN: 'PA',
   PNG: 'PG',
   PRY: 'PY',
   PER: 'PE',
   PHL: 'PH',
   PCN: 'PN',
   POL: 'PL',
   PRT: 'PT',
   PRI: 'PR',
   QAT: 'QA',
   REU: 'RE',
   ROU: 'RO',
   RUS: 'RU',
   RWA: 'RW',
   BLM: 'BL',
   SHN: 'SH',
   KNA: 'KN',
   LCA: 'LC',
   MAF: 'MF',
   SPM: 'PM',
   VCT: 'VC',
   WSM: 'WS',
   SMR: 'SM',
   STP: 'ST',
   SAU: 'SA',
   SEN: 'SN',
   SRB: 'RS',
   SYC: 'SC',
   SLE: 'SL',
   SGP: 'SG',
   SXM: 'SX',
   SVK: 'SK',
   SVN: 'SI',
   SLB: 'SB',
   SOM: 'SO',
   ZAF: 'ZA',
   SGS: 'GS',
   SSD: 'SS',
   ESP: 'ES',
   LKA: 'LK',
   SDN: 'SD',
   SUR: 'SR',
   SJM: 'SJ',
   SWE: 'SE',
   CHE: 'CH',
   SYR: 'SY',
   TWN: 'TW',
   TJK: 'TJ',
   TZA: 'TZ',
   THA: 'TH',
   TLS: 'TL',
   TGO: 'TG',
   TKL: 'TK',
   TON: 'TO',
   TTO: 'TT',
   TUN: 'TN',
   TUR: 'TR',
   TKM: 'TM',
   TCA: 'TC',
   TUV: 'TV',
   UGA: 'UG',
   UKR: 'UA',
   ARE: 'AE',
   GBR: 'GB',
   USA: 'US',
   UMI: 'UM',
   URY: 'UY',
   UZB: 'UZ',
   VUT: 'VU',
   VEN: 'VE',
   VNM: 'VN',
   VGB: 'VG',
   VIR: 'VI',
   WLF: 'WF',
   ESH: 'EH',
   YEM: 'YE',
   ZMB: 'ZM',
   ZWE: 'ZW',
   ZZZ: 'ZZ',
};

export const getCountryCodeFromAlphaThree = (AlphaThreeCode:string): string => countryAlphaTwoCodes[AlphaThreeCode];

export default countries;
